# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReliefProject
                                 A QGIS plugin
 This plugin suggests suitable geographic locations for setting up relief camps.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-22
        copyright            : (C) 2018 by Shyam Shristy Dahiya Inc.
        email                : ydsd97@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReliefProject class from file ReliefProject.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .relief_linker import ReliefProject
    return ReliefProject(iface)
